# Generated by Django 4.2.4 on 2023-09-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_number", models.PositiveIntegerField(default=1)),
                ("subject", models.TextField()),
                ("total_mark", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_number", models.PositiveIntegerField(default=1)),
                ("total_mark", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marking_assistant_app.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criteria_number", models.PositiveIntegerField(default=1)),
                ("description", models.TextField()),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feedback_comment", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marking_assistant_app.task",
                    ),
                ),
            ],
        ),
    ]
