# Generated by Django 4.2.4 on 2023-09-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marking_assistant_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="subject",
            new_name="subject_code",
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="total_mark",
            new_name="total_marks",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="total_mark",
            new_name="total_marks",
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("assignment_number", "subject_code")},
        ),
        migrations.AlterUniqueTogether(
            name="criteria",
            unique_together={("task", "criteria_number")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("assignment", "task_number")},
        ),
    ]
