# Generated by Django 4.2.4 on 2023-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marking_assistant_app",
            "0002_rename_subject_assignment_subject_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="subject_code",
            field=models.CharField(max_length=10),
        ),
    ]
