# Generated by Django 4.2.4 on 2023-09-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marking_assistant_app", "0003_alter_assignment_subject_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="criteria",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="criteria",
            name="criteria_number",
        ),
    ]
